from __future__ import annotations

import json
from pathlib import Path


def main() -> None:
    data_dir = Path(__file__).resolve().parents[1] / "data"
    data_dir.mkdir(parents=True, exist_ok=True)

    vendors = [
        {
            "VendorID": "V001",
            "Name": "Holiday Supplies Inc.",
            "PhoneNumber": "+1-206-555-0148",
            "Email": "orders@holidaysupplies.example",
            "LeadTimeDays": 12,
            "MinimumOrder": 500,
            "Rating": 4.6,
        },
        {
            "VendorID": "V002",
            "Name": "Evergreen Wholesale",
            "PhoneNumber": "+1-503-555-0184",
            "Email": "sales@evergreenwholesale.example",
            "LeadTimeDays": 8,
            "MinimumOrder": 300,
            "Rating": 4.3,
        },
        {
            "VendorID": "V003",
            "Name": "Aurora Electronics",
            "PhoneNumber": "+1-408-555-0172",
            "Email": "supply@auroraelectronics.example",
            "LeadTimeDays": 15,
            "MinimumOrder": 800,
            "Rating": 4.5,
        },
        {
            "VendorID": "V004",
            "Name": "Northwind Distribution",
            "PhoneNumber": "+1-312-555-0199",
            "Email": "accounts@northwinddist.example",
            "LeadTimeDays": 10,
            "MinimumOrder": 400,
            "Rating": 4.1,
        },
    ]

    inventory_items = [
        {
            "SKU": "HOL-CTREE-6FT",
            "Name": "Premium 6ft Christmas Tree",
            "Category": "Holiday",
            "CurrentStock": 15,
            "ReorderPoint": 40,
            "DailySalesVelocity": 8.2,
            "UnitCost": 45.0,
            "VendorID": "V001",
            "LeadTimeDays": 12,
            "LastUpdated": "2026-02-03",
        },
        {
            "SKU": "HOL-CTREE-7FT",
            "Name": "Deluxe 7ft Christmas Tree",
            "Category": "Holiday",
            "CurrentStock": 9,
            "ReorderPoint": 35,
            "DailySalesVelocity": 6.5,
            "UnitCost": 62.0,
            "VendorID": "V001",
            "LeadTimeDays": 12,
            "LastUpdated": "2026-02-03",
        },
        {
            "SKU": "HOL-ORN-RED-24",
            "Name": "Red Ornament Set (24pc)",
            "Category": "Holiday",
            "CurrentStock": 60,
            "ReorderPoint": 100,
            "DailySalesVelocity": 12.0,
            "UnitCost": 4.5,
            "VendorID": "V001",
            "LeadTimeDays": 12,
            "LastUpdated": "2026-02-03",
        },
        {
            "SKU": "HOL-LIGHTS-WHITE-100",
            "Name": "White LED String Lights (100ct)",
            "Category": "Holiday",
            "CurrentStock": 120,
            "ReorderPoint": 80,
            "DailySalesVelocity": 10.0,
            "UnitCost": 6.5,
            "VendorID": "V002",
            "LeadTimeDays": 8,
            "LastUpdated": "2026-02-03",
        },
        {
            "SKU": "HOL-WREATH-24",
            "Name": "Pine Wreath 24in",
            "Category": "Holiday",
            "CurrentStock": 25,
            "ReorderPoint": 50,
            "DailySalesVelocity": 5.5,
            "UnitCost": 8.75,
            "VendorID": "V002",
            "LeadTimeDays": 8,
            "LastUpdated": "2026-02-03",
        },
        {
            "SKU": "ELEC-SPKR-BT-MINI",
            "Name": "Bluetooth Mini Speaker",
            "Category": "Electronics",
            "CurrentStock": 40,
            "ReorderPoint": 60,
            "DailySalesVelocity": 7.4,
            "UnitCost": 18.0,
            "VendorID": "V003",
            "LeadTimeDays": 15,
            "LastUpdated": "2026-02-03",
        },
        {
            "SKU": "ELEC-HEADPHONES-ANC",
            "Name": "Noise Canceling Headphones",
            "Category": "Electronics",
            "CurrentStock": 22,
            "ReorderPoint": 45,
            "DailySalesVelocity": 4.1,
            "UnitCost": 58.0,
            "VendorID": "V003",
            "LeadTimeDays": 15,
            "LastUpdated": "2026-02-03",
        },
        {
            "SKU": "ELEC-USBHUB-7P",
            "Name": "7-Port USB Hub",
            "Category": "Electronics",
            "CurrentStock": 55,
            "ReorderPoint": 70,
            "DailySalesVelocity": 6.8,
            "UnitCost": 12.5,
            "VendorID": "V003",
            "LeadTimeDays": 15,
            "LastUpdated": "2026-02-03",
        },
        {
            "SKU": "ELEC-CAM-WEBCAM-HD",
            "Name": "HD Webcam",
            "Category": "Electronics",
            "CurrentStock": 18,
            "ReorderPoint": 30,
            "DailySalesVelocity": 3.6,
            "UnitCost": 28.0,
            "VendorID": "V003",
            "LeadTimeDays": 15,
            "LastUpdated": "2026-02-03",
        },
        {
            "SKU": "HOME-PILLOW-SET",
            "Name": "Throw Pillow Set",
            "Category": "Home",
            "CurrentStock": 48,
            "ReorderPoint": 60,
            "DailySalesVelocity": 4.9,
            "UnitCost": 9.8,
            "VendorID": "V002",
            "LeadTimeDays": 8,
            "LastUpdated": "2026-02-03",
        },
        {
            "SKU": "HOME-BLANKET-FLEECE",
            "Name": "Fleece Blanket",
            "Category": "Home",
            "CurrentStock": 32,
            "ReorderPoint": 55,
            "DailySalesVelocity": 3.2,
            "UnitCost": 14.5,
            "VendorID": "V002",
            "LeadTimeDays": 8,
            "LastUpdated": "2026-02-03",
        },
        {
            "SKU": "HOME-CANDLE-VAN",
            "Name": "Vanilla Candle",
            "Category": "Home",
            "CurrentStock": 75,
            "ReorderPoint": 90,
            "DailySalesVelocity": 6.1,
            "UnitCost": 5.2,
            "VendorID": "V002",
            "LeadTimeDays": 8,
            "LastUpdated": "2026-02-03",
        },
        {
            "SKU": "HOME-STORAGE-BIN-L",
            "Name": "Storage Bin Large",
            "Category": "Home",
            "CurrentStock": 28,
            "ReorderPoint": 45,
            "DailySalesVelocity": 2.7,
            "UnitCost": 11.0,
            "VendorID": "V002",
            "LeadTimeDays": 8,
            "LastUpdated": "2026-02-03",
        },
        {
            "SKU": "OUT-CHAIR-FOLD",
            "Name": "Folding Camp Chair",
            "Category": "Outdoor",
            "CurrentStock": 14,
            "ReorderPoint": 30,
            "DailySalesVelocity": 2.9,
            "UnitCost": 19.5,
            "VendorID": "V002",
            "LeadTimeDays": 8,
            "LastUpdated": "2026-02-03",
        },
        {
            "SKU": "OUT-LANTERN-LED",
            "Name": "LED Camping Lantern",
            "Category": "Outdoor",
            "CurrentStock": 26,
            "ReorderPoint": 40,
            "DailySalesVelocity": 3.4,
            "UnitCost": 13.8,
            "VendorID": "V002",
            "LeadTimeDays": 8,
            "LastUpdated": "2026-02-03",
        },
        {
            "SKU": "OUT-GRILL-TOOLSET",
            "Name": "Grill Tool Set",
            "Category": "Outdoor",
            "CurrentStock": 21,
            "ReorderPoint": 35,
            "DailySalesVelocity": 2.2,
            "UnitCost": 16.0,
            "VendorID": "V002",
            "LeadTimeDays": 8,
            "LastUpdated": "2026-02-03",
        },
        {
            "SKU": "TOY-BLOCKS-100",
            "Name": "Building Blocks 100pc",
            "Category": "Toys",
            "CurrentStock": 52,
            "ReorderPoint": 70,
            "DailySalesVelocity": 5.7,
            "UnitCost": 12.0,
            "VendorID": "V004",
            "LeadTimeDays": 10,
            "LastUpdated": "2026-02-03",
        },
        {
            "SKU": "TOY-DRONE-MINI",
            "Name": "Mini Quadcopter",
            "Category": "Toys",
            "CurrentStock": 11,
            "ReorderPoint": 25,
            "DailySalesVelocity": 2.1,
            "UnitCost": 26.0,
            "VendorID": "V004",
            "LeadTimeDays": 10,
            "LastUpdated": "2026-02-03",
        },
        {
            "SKU": "TOY-PLUSH-BEAR",
            "Name": "Plush Bear 12in",
            "Category": "Toys",
            "CurrentStock": 38,
            "ReorderPoint": 55,
            "DailySalesVelocity": 4.4,
            "UnitCost": 7.5,
            "VendorID": "V004",
            "LeadTimeDays": 10,
            "LastUpdated": "2026-02-03",
        },
        {
            "SKU": "TOY-BOARD-CLASSIC",
            "Name": "Classic Board Game",
            "Category": "Toys",
            "CurrentStock": 19,
            "ReorderPoint": 35,
            "DailySalesVelocity": 3.0,
            "UnitCost": 14.0,
            "VendorID": "V004",
            "LeadTimeDays": 10,
            "LastUpdated": "2026-02-03",
        },
        {
            "SKU": "APP-TSHIRT-COT-M",
            "Name": "Cotton T-Shirt M",
            "Category": "Apparel",
            "CurrentStock": 80,
            "ReorderPoint": 120,
            "DailySalesVelocity": 9.1,
            "UnitCost": 6.0,
            "VendorID": "V004",
            "LeadTimeDays": 10,
            "LastUpdated": "2026-02-03",
        },
        {
            "SKU": "APP-HOODIE-GREY-L",
            "Name": "Grey Hoodie L",
            "Category": "Apparel",
            "CurrentStock": 34,
            "ReorderPoint": 60,
            "DailySalesVelocity": 4.0,
            "UnitCost": 18.5,
            "VendorID": "V004",
            "LeadTimeDays": 10,
            "LastUpdated": "2026-02-03",
        },
        {
            "SKU": "APP-SOCKS-SPORT-3",
            "Name": "Sport Socks 3pk",
            "Category": "Apparel",
            "CurrentStock": 95,
            "ReorderPoint": 130,
            "DailySalesVelocity": 11.2,
            "UnitCost": 3.2,
            "VendorID": "V004",
            "LeadTimeDays": 10,
            "LastUpdated": "2026-02-03",
        },
        {
            "SKU": "KIT-PAN-NONSTICK-10",
            "Name": "Nonstick Pan 10in",
            "Category": "Kitchen",
            "CurrentStock": 27,
            "ReorderPoint": 45,
            "DailySalesVelocity": 3.3,
            "UnitCost": 15.0,
            "VendorID": "V002",
            "LeadTimeDays": 8,
            "LastUpdated": "2026-02-03",
        },
        {
            "SKU": "KIT-KNIFE-SET-6",
            "Name": "Kitchen Knife Set 6pc",
            "Category": "Kitchen",
            "CurrentStock": 16,
            "ReorderPoint": 28,
            "DailySalesVelocity": 2.5,
            "UnitCost": 22.0,
            "VendorID": "V002",
            "LeadTimeDays": 8,
            "LastUpdated": "2026-02-03",
        },
        {
            "SKU": "KIT-MUG-SET-4",
            "Name": "Ceramic Mug Set 4pc",
            "Category": "Kitchen",
            "CurrentStock": 42,
            "ReorderPoint": 65,
            "DailySalesVelocity": 4.8,
            "UnitCost": 9.0,
            "VendorID": "V002",
            "LeadTimeDays": 8,
            "LastUpdated": "2026-02-03",
        },
        {
            "SKU": "BEAUTY-SERUM-VITC",
            "Name": "Vitamin C Serum",
            "Category": "Beauty",
            "CurrentStock": 33,
            "ReorderPoint": 50,
            "DailySalesVelocity": 3.7,
            "UnitCost": 10.5,
            "VendorID": "V004",
            "LeadTimeDays": 10,
            "LastUpdated": "2026-02-03",
        },
        {
            "SKU": "BEAUTY-CREAM-HAND",
            "Name": "Hand Cream 100ml",
            "Category": "Beauty",
            "CurrentStock": 58,
            "ReorderPoint": 80,
            "DailySalesVelocity": 5.9,
            "UnitCost": 4.8,
            "VendorID": "V004",
            "LeadTimeDays": 10,
            "LastUpdated": "2026-02-03",
        },
        {
            "SKU": "OFF-NOTEBOOK-A5",
            "Name": "A5 Notebook",
            "Category": "Office",
            "CurrentStock": 110,
            "ReorderPoint": 140,
            "DailySalesVelocity": 12.5,
            "UnitCost": 2.2,
            "VendorID": "V004",
            "LeadTimeDays": 10,
            "LastUpdated": "2026-02-03",
        },
        {
            "SKU": "OFF-MOUSE-WIRELESS",
            "Name": "Wireless Mouse",
            "Category": "Office",
            "CurrentStock": 24,
            "ReorderPoint": 40,
            "DailySalesVelocity": 3.9,
            "UnitCost": 13.0,
            "VendorID": "V003",
            "LeadTimeDays": 15,
            "LastUpdated": "2026-02-03",
        },
    ]

    if len(inventory_items) != 30:
        raise ValueError(f"Expected 30 inventory items, got {len(inventory_items)}")

    payloads = {
        "mock_inventory.json": inventory_items,
        "mock_vendors.json": vendors,
        "mock_vendor_call_logs.json": [],
        "mock_replenishment_plans.json": [],
    }

    for filename, payload in payloads.items():
        path = data_dir / filename
        path.write_text(json.dumps(payload, indent=2), encoding="utf-8")

    summary = {
        "inventory_items": len(inventory_items),
        "vendors": len(vendors),
    }
    print(json.dumps(summary, indent=2))


if __name__ == "__main__":
    main()
