# coding: utf-8

"""
    Selling Partner API for FBA Inventory

    The Selling Partner API for FBA Inventory lets you programmatically retrieve information about inventory in Amazon's fulfillment network.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.reserved_quantity import ReservedQuantity  # noqa: E501
from swagger_client.rest import ApiException


class TestReservedQuantity(unittest.TestCase):
    """ReservedQuantity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testReservedQuantity(self):
        """Test ReservedQuantity"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.reserved_quantity.ReservedQuantity()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
