# coding: utf-8

"""
    Selling Partner API for FBA Inventory

    The Selling Partner API for FBA Inventory lets you programmatically retrieve information about inventory in Amazon's fulfillment network.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.create_inventory_item_request import CreateInventoryItemRequest  # noqa: E501
from swagger_client.rest import ApiException


class TestCreateInventoryItemRequest(unittest.TestCase):
    """CreateInventoryItemRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateInventoryItemRequest(self):
        """Test CreateInventoryItemRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.create_inventory_item_request.CreateInventoryItemRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
