# coding: utf-8

"""
    Selling Partner API for FBA Inventory

    The Selling Partner API for FBA Inventory lets you programmatically retrieve information about inventory in Amazon's fulfillment network.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.fba_inventory_api import FbaInventoryApi  # noqa: E501
from swagger_client.rest import ApiException


class TestFbaInventoryApi(unittest.TestCase):
    """FbaInventoryApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.fba_inventory_api.FbaInventoryApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_inventory(self):
        """Test case for add_inventory

        """
        pass

    def test_create_inventory_item(self):
        """Test case for create_inventory_item

        """
        pass

    def test_delete_inventory_item(self):
        """Test case for delete_inventory_item

        """
        pass

    def test_get_inventory_summaries(self):
        """Test case for get_inventory_summaries

        """
        pass


if __name__ == '__main__':
    unittest.main()
